---
- name: Has alacritty config dir
  file:
    path: ~/.config/alacritty
    state: directory

- name: Has config script
  template   :
      src    : ./alacritty/templates/alacritty.yml
      dest   : ~/.config/alacritty/alacritty.yml
      backup : false
      
- name: Has fonts dir
  file:
    path: ~/.fonts
    state: directory

- name: Has font downloaded
  get_url:
      dest: ~/.fonts
      url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/Inconsolata/complete/Inconsolata%20Nerd%20Font%20Complete%20Mono.otf

- name: Has font downloaded
  get_url:
      dest: ~/.fonts
      url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/Inconsolata/complete/Inconsolata%20Nerd%20Font%20Complete.otf

- name: Has font downloaded
  get_url:
      dest: ~/.fonts
      url: https://github.com/be5invis/Iosevka/releases/download/v2.0.0/02-iosevka-term-2.0.0.zip

- name: Has font extracted
  shell: "cd ~/.fonts && atool -x 02-iosevka-term-2.0.0.zip"
