- name: Has configured PS1 
  tags: bash
  lineinfile:
    line: ' export PS1="\[\e[1;33m\]:\[\e[0;38m\]"'
    dest: "{{ bash_config_dir }}/overall"
    state: present
    regexp: 'export PS1=.*'
    create: yes

- name: Has configured PS1 for root
  become: true
  tags: [ bash, system ]
  lineinfile:
    line: 'export PS1="\[\e[3;33m\]:\[\e[0;38m\]"'
    dest: "/root/.bashrc"
    state: present
    regexp: 'export PS1=.*'
    create: yes

- name: Has config for git
  tags: bash
  blockinfile:
    marker: "# {mark} git aliases (ansible managed)"
    dest: "{{ bash_config_dir }}/git"
    create: yes
    content: |
        alias gs='git status'
        alias gc='git commit'
        alias ga='git add'
        alias gp='git pull'
        alias gP='git push'

- name: Has aliases for tmux 
  tags: bash
  blockinfile:
    dest: "{{ bash_config_dir }}/tmux"
    create: yes
    content: |
        tf_old() {
            if ! [[ -z "$TMUX" ]]
            then
                tmux detach
            fi
            tmux attach-session -t $(tmux list-session -F "#{session_name}" | fzf)
        }
        alias ts='tmux list-session'
        alias ta='tmux attach-session -t'
        alias td='tmux detach'
        alias tf='tmux attach-session -t $(tmux list-session -F "#{session_name}" | fzf)'
        alias tn='tmux new-session'
        alias tc='tmux new-session -s'

- name: Has .bashrc sourced
  tags: bash 
  lineinfile:
    dest: ~/.bashrc
    create: yes
    line: "source {{ bash_config_dir }}/{{ item }}"
  with_items:
    - tmux
    - overall
    - git

- name: Has clear command on terminanl start for ranger 
  tags: bash 
  lineinfile:
    dest: ~/.bashrc
    create: yes
    line: "clear"
