- name: check if npm is installed
  package:
    name: npm
    state: present

- name: install nvm to home dir
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
    
- name: install node
  shell: nvm install stable 
