---
- hosts: localhost
  connection: local
  roles:
    - jdk
    - fzf
    - tmux
    - ansible 
    - bash
    - vim
    - the_silver_searcher 
    - ansible_hacking
    - scripts
    - clipster
    - gradle
    - xcape
    - groovy
    - lf
    - alacritty
    - docker
    - tools
    - i3
    - zsh
