---
- hosts: localhost
  connection: local
  roles:
    - git
    - fzf
    - tmux
    - ansible 
    - bash
    - vim
    - ranger
    - ranger-fzf
    - urxvt
    - the_silver_searcher 
    - ansible_hacking
    - scripts
    - ranger-fzf-scripts
    - clipster
