---
- hosts: localhost
  connection: local
  tasks:
    - name: Load config
      tags: always
      include_vars:
        dir: "config/{{ ansible_hostname }}"

    - include_tasks: "./plays/{{ item }}/install.yml"
      tags: install
      with_items: "{{ plays }}"

    - include_tasks: "./plays/{{ item }}/config.yml"
      tags: config
      with_items: "{{ plays }}"
