---
- hosts: localhost
  connection: local
  tasks:
    - name: Load config
      tags: always
      include_vars:
        dir: "config/{{ ansible_hostname }}"

- import_playbook: overall/play.yml
#- import_playbook: neovim/play.yml
