---
- name: Has python-dev
  package:
    name: python-dev 
    state: present

- name: Has git
  package:
    name: git
    state: present

- name: Has pyyaml installed
  pip:
    name: pyyaml
    executable: pip2

- name: Has jinja2 installed
  pip:
    name: jinja2
    executable: pip2

- name: Has nose installed
  pip:
    name: nose
    executable: pip2

- name: Has passlib installed
  pip:
    name: passlib
    executable: pip2

- name: Has pycrypto installed
  pip:
    name: pycrypto
    executable: pip2

- name: Has cloned ansible sources with ansible-hacking
  git:
    repo: git@github.com:ansible/ansible.git
    dest: ~/Coding/soft/ansible

- name: Has alias for ansible test-module
  blockinfile:
    marker: "# {mark} ansible test-module alias (ansible managed)"
    dest: ~/.bashrc
    content: |
        test() {
            source /home/stcarolas/Coding/soft/ansible/hacking/env-setup
            /home/stcarolas/Coding/soft/ansible/hacking/test-module -m $1 -a $2
        }
