---
- name: Has gradle config dir
  tags: gradle
  file:
    path: ~/.gradle
    state: directory

- name: Has init script
  tags: gradle
  template   :
      src    : templates/init.gradle
      dest   : ~/.gradle/init.gradle
      backup : yes
# tasks file for gradle
