- name: Has right i3 config
  lineinfile  :
      dest    : ~/.config/i3/config
      create  : yes
      line    : "exec --no-startup-id feh --bg-fill ~/Pictures/Wall/back"
      regexp  : "exec --no-startup-id feh .*"
