---
# tasks file for i3
- name: Has i3 config
  tags: i3
  copy:
    src: ./i3/templates/
    dest: ~/.config/i3/

- name: Has XKB config
  become: true
  tags: i3
  copy:
    src: ./i3/xkb/
    dest: /usr/share/X11/xkb/symbols


- name: Has i3blocks config
  tags: i3
  shell: "cp /etc/i3blocks.conf ~/.config/i3/i3blocks.conf"
