- name: Has alias for ansible-playbook
  lineinfile:
    line: "alias gp = ansible-playbook"
    dest: ~/.bashrc
    state: present
    regexp: "alias gp = ansible-playbook"

- name: Has rg function for opening ranger
  blockinfile:
    dest: ~/.bashrc
    marker: "# {mark} ff function for opening ranger (ansible managed)"
    create: yes
    content: |
        rg() {
            if [ -z "$RANGER_LEVEL" ]
            then
                ranger
            else
                exit
            fi
        }
