- name: Has local Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
  tags:
    - plugins 
    - vim

- name: Has configured vimrc for Vundle, part1  
  blockinfile: 
    create: yes
    dest: ~/.config/vim/plugins
    marker: '"{mark} vundle start block'
    content: |
        set nocompatible
        filetype off
        set rtp+=~/.vim/bundle/Vundle.vim
        call vundle#begin()
        Plugin 'VundleVim/Vundle.vim'
  tags:
    - plugins
    - vim

- name: Has configured vimrc for Vundle, part2  
  blockinfile: 
    dest: ~/.config/vim/plugins
    marker: '"{mark} vundle end block'
    content: |
        call vundle#end()
        filetype plugin indent on
  tags:
    - plugins
    - vim

- name: Has installed plugins
  tags:
    - plugins
    - vim
  notify: install plugins
  lineinfile:
    insertafter: 'END vundle start block'
    line: Plugin '{{ item }}'
    dest: ~/.config/vim/plugins
    state: present
    regexp: Plugin '{{ item }}' 
  with_items:
    - easymotion/vim-easymotion
    - junegunn/fzf.vim
    - majutsushi/tagbar
    - scrooloose/nerdcommenter
    - Chiel92/vim-autoformat
    - bkad/CamelCaseMotion
    - Shougo/denite.nvim
    - artur-shaik/vim-javacomplete2
    - airblade/vim-rooter
    - scrooloose/nerdtree
    - jistr/vim-nerdtree-tabs
    - jiangmiao/auto-pairs
    - vim-syntastic/syntastic
    - cosminadrianpopescu/vim-sql-workbench
