---
- name: Has ranger
  become: true
  tags: ranger, system
  package:
    name: ranger
    state: present

- name: Has rg function in bashrc for opening ranger
  tags: ranger
  blockinfile:
    dest: "{{ bash_config_dir }}/ranger"
    marker: "# {mark} ff function for opening ranger (ansible managed)"
    create: yes
    content: |
        clear
        rg() {
            if [ -z "$RANGER_LEVEL" ]
            then
                ranger
            else
                exit
            fi
        }

- name: Has hotkey for Go to Projects
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    create: yes
    line: "map gp      cd ~/Coding/projects"
    state: present
    regexp: "map gp.*"

- name: Has ; as leader key
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "unmap ;"
    state: present

- name: Has hotkey for Go to Downloads
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "map gd      cd ~/Downloads"
    state: present
    regexp: "map gd.*"

- name: Has colorscheme setted
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "set colorscheme snow"
    state: present
    regexp: "set colorscheme.*"

- name: Has .bashrc sourced
  tags: ranger
  lineinfile:
    dest: ~/.bashrc
    create: yes
    line: "source {{ bash_config_dir }}/ranger"
