- name: Has zsh config
  copy:
    src: templates/config
    dest: ~/.zshrc
    force: yes
    
- name: Has zsh configs
  copy:
    src: templates/configs/
    dest: ~/.config/zsh/
    force: yes

- name: Has zplug installed
  command: ls ~/.zplug
  ignore_errors: True
  register: has_zplug

- name: Install zplug
  when: has_zplug is failed
  shell: "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"

