---
- name: Has ranger
  tags: ranger
  package:
    name: ranger
    state: present

- name: Has rg function in bashrc for opening ranger
  tags: ranger
  blockinfile:
    dest: "{{ bashrc_path }}"
    marker: "# {mark} ff function for opening ranger (ansible managed)"
    create: yes
    content: |
        rg() {
            if [ -z "$RANGER_LEVEL" ]
            then
                ranger
            else
                exit
            fi
        }

- name: Has hotkey for vim-fzf
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "map \\f      shell vim $(fzf)"
    state: present
    regexp: "map \\f.*"

- name: Has hotkey for Go to Projects
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "map gp      cd ~/Coding/projects"
    state: present
    regexp: "map gp.*"

- name: Has hotkey for Go to Downloads
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "map gd      cd ~/Downloads"
    state: present
    regexp: "map gd.*"
