---
- name: install ranger
  package:
    name: ranger
    state: present

- name: Has rg function in bashrc for opening ranger
  blockinfile:
    dest: ~/.bashrc
    marker: "# {mark} ff function for opening ranger (ansible managed)"
    create: yes
    content: |
        rg() {
            if [ -z "$RANGER_LEVEL" ]
            then
                ranger
            else
                exit
            fi
        }
