---
- name: install ranger
  package:
    name: ranger
    state: present

- name: Has rg function in bashrc for opening ranger
  blockinfile:
    dest: ~/.bashrc
    marker: "# {mark} ff function for opening ranger (ansible managed)"
    create: yes
    content: |
        rg() {
            if [ -z "$RANGER_LEVEL" ]
            then
                ranger
            else
                exit
            fi
        }

- name: Has hotkey for vim-fzf
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "map \\f      shell vim $(fzf)"
    state: present
    regexp: "map \\f.*"

- name: Has hotkey for Go to Projects
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "map gp      cd ~/Coding/projects"
    state: present
    regexp: "map gp.*"
