---
- name: Has conky config dir
  file:
    path: ~/.config/dunst
    state: directory

- name: Has config script
  template   :
      src    : ./dunst/templates/dunstrc
      dest   : ~/.config/dunst/dunstrc
      backup : false
