---
# tasks file for xkb
- name: Has xkb config dir
  tags: xkb
  file:
    path:  "{{ xkb_config_dir }}/symbols"
    state: directory

- name: Has configs for interactive session
  tags: xkb
  copy   :
      src:    templates/custom
      dest:   "{{ xkb_config_dir }}/symbols/"

- name: Has configs in i3
  tags: xkb
  blockinfile:
    dest: "~/.config/i3/config"
    create: yes
    content: |
        exec --no-startup-id 'sleep 4 && setxkbmap -symbols custom -print | xkbcomp -I$HOME/.config/xkb - "${DISPLAY%%.*}"'
