---
- name: Has tmux
  become: true
  tags: tmux, system
  package  :
    name   : tmux
    state  : present

- name: Has global options setted 
  tags: tmux
  lineinfile  :
      dest    : "{{ tmux_global_config }}"
      create  : yes
      line    : "set -g {{ item.name }} {{ item.value }}"
  with_items:
      - { name: base-index,             value: 1     }
      - { name: status,                 value: off   }
      - { name: set-titles,             value: on    }
      - { name: allow-rename,           value: off   }

- name: Has window options setted 
  tags: tmux
  lineinfile  :
      dest    : "{{ tmux_global_config }}"
      create  : yes
      line    : "setw -g {{ item.name }} {{ item.value }}"
  with_items:
      - { name: xterm-keys,             value: on   }
      - { name: mode-keys,              value: vi   }
      - { name: automatic-rename,       value: off  }
      - { name: pane-base-index,        value: 1    }
      - { name: aggressive-resize,      value: on   }

- name: Has switch panes hotkeys setted 
  tags: tmux
  blockinfile :
      dest    : "{{ tmux_global_config }}"
      create  : yes
      marker  : "# {mark} Alt-vim keys for switching panes"
      content : |
          bind -n M-h select-pane -L
          bind -n M-j select-pane -D
          bind -n M-k select-pane -U
          bind -n M-l select-pane -R

- name: Has switch panes hotkeys setted 
  tags: tmux
  blockinfile :
      dest    : "{{ tmux_global_config }}"
      create  : yes
      marker  : "# {mark} Alt-Num keys for switching windows"
      content : |
           bind-key    -n M-1                select-window -t :=1
           bind-key    -n M-2                select-window -t :=2
           bind-key    -n M-3                select-window -t :=3
           bind-key    -n M-4                select-window -t :=4
           bind-key    -n M-5                select-window -t :=5
           bind-key    -n M-6                select-window -t :=6
           bind-key    -n M-7                select-window -t :=7
           bind-key    -n M-8                select-window -t :=8

- name: Has prefixes setted 
  tags: tmux
  blockinfile :
      dest    : "{{ tmux_global_config }}"
      create  : yes
      marker  : "# {mark} prefixes"
      content : |
          set-option -g prefix C-h
          bind-key a send-prefix
