---
- name: Has conky config dir
  file:
    path: ~/.config/networkmanager-dmenu/
    state: directory

- name: Has config script
  template   :
      src    : ./networkmanager_dmenu/templates/config.ini
      dest   : ~/.config/networkmanager_dmenu/config.ini
      backup : false
