---
# tasks file for i3
- name: Has neovim config dir
  file:
    path: ~/.config/nvim/
    state: directory

- name: Has neovim global config
  copy:
    src: ./plays/neovim/templates/init.vim
    dest: ~/.config/nvim/init.vim
