---
- name: Has downloads dir
  file:
    path:  ~/Downloads
    state: directory

- name: Has line for downloads in fstab
  become: true
  lineinfile  :
      dest    : /etc/fstab
      create  : yes
      line    : "tmpfs /home/stCarolas/Downloads                   tmpfs     defaults        0 0"
