---
- name: Has downloads dir
  file:
    path:  ~/Coding/projects/
    state: directory

- name: Has line in fstab
  become: true
  lineinfile  :
      dest    : /etc/fstab
      create  : yes
      line    : "tmpfs /home/stCarolas/Coding/projects/                   tmpfs     defaults        0 0"
